serviceAccounts:
  server:
    create: true
    name: ${service_account_amp_ingest_name}
    annotations:
      eks.amazonaws.com/role-arn: "${server_annotation}"

alertmanager:
  image:
    repository: ${alert_manager_repo_url}
    tag: ${alert_manager_image_tag}
  nodeSelector:
    kubernetes.io/os: linux

configmapReload:
  image:
    repository: ${configmap_reload_repo_url}
    tag: ${configmap_reload_image_tag}

kubeStateMetrics:
  enabled: true

kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: linux

nodeExporter:
  image:
    repository: ${node_exporter_repo_url}
    tag: ${node_exporter_image_tag}
  nodeSelector:
    kubernetes.io/os: linux


server:
  remoteWrite:
    - url: ${amp_workspace_url}
      sigv4:
        region: ${region}
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
  retention: 1h

  image:
    repository: ${prometheus_repo_url}
    tag: ${prometheus_image_tag}

  global:
    scrape_interval: 15s

  nodeSelector:
    kubernetes.io/os: linux

pushgateway:
  image:
    repository: ${pushgateway_repo_url}
    tag: ${pushgateway_image_tag}
  nodeSelector:
    kubernetes.io/os: linux

nodeSelector:
  kubernetes.io/os: linux
